# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import test_visualize

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/healthcare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setStyleSheet("    #icon_only_widget {\n"
"        background-color: #313a46;\n"
"        width:50px;\n"
"    }\n"
"\n"
"    #icon_only_widget QPushButton, QLabel {\n"
"        height:50px;\n"
"        border:none;\n"
"        background-color: #313a46;\n"
"        /* border-bottom: 1px solid #b0b0b0; */\n"
"    }\n"
"\n"
"    #icon_only_widget QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_label_1 = QtWidgets.QLabel(self.icon_only_widget)
        self.logo_label_1.setMinimumSize(QtCore.QSize(64, 64))
        self.logo_label_1.setMaximumSize(QtCore.QSize(64, 64))
        self.logo_label_1.setStyleSheet("    #logo_label_1 {\n"
"    background-color: rgba(0, 0, 0,0);\n"
"        padding: 5px\n"
"    }")
        self.logo_label_1.setText("")
        self.logo_label_1.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/healthcare.png"))
        self.logo_label_1.setScaledContents(True)
        self.logo_label_1.setObjectName("logo_label_1")
        self.horizontalLayout_3.addWidget(self.logo_label_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.home_btn_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_btn_1.setStyleSheet("")
        self.home_btn_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/home_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/home_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.home_btn_1.setIcon(icon1)
        self.home_btn_1.setIconSize(QtCore.QSize(40, 40))
        self.home_btn_1.setCheckable(True)
        self.home_btn_1.setAutoExclusive(True)
        self.home_btn_1.setObjectName("home_btn_1")
        self.verticalLayout.addWidget(self.home_btn_1)
        self.newprofile_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.newprofile_btn_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newprofile_btn_1.setStyleSheet("")
        self.newprofile_btn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/add-user_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/add-user_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.newprofile_btn_1.setIcon(icon2)
        self.newprofile_btn_1.setIconSize(QtCore.QSize(40, 40))
        self.newprofile_btn_1.setCheckable(True)
        self.newprofile_btn_1.setAutoExclusive(True)
        self.newprofile_btn_1.setObjectName("newprofile_btn_1")
        self.verticalLayout.addWidget(self.newprofile_btn_1)
        self.display_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.display_btn_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.display_btn_1.setStyleSheet("")
        self.display_btn_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/heartbeat_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/heartbeat_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.display_btn_1.setIcon(icon3)
        self.display_btn_1.setIconSize(QtCore.QSize(40, 40))
        self.display_btn_1.setCheckable(True)
        self.display_btn_1.setAutoExclusive(True)
        self.display_btn_1.setObjectName("display_btn_1")
        self.verticalLayout.addWidget(self.display_btn_1)
        self.uart_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.uart_btn_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.uart_btn_1.setStyleSheet("")
        self.uart_btn_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/two-arrows_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/two-arrows_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.uart_btn_1.setIcon(icon4)
        self.uart_btn_1.setIconSize(QtCore.QSize(40, 40))
        self.uart_btn_1.setCheckable(True)
        self.uart_btn_1.setAutoExclusive(True)
        self.uart_btn_1.setObjectName("uart_btn_1")
        self.verticalLayout.addWidget(self.uart_btn_1)
        spacerItem = QtWidgets.QSpacerItem(20, 375, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.exit_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.exit_btn_1.setStyleSheet("")
        self.exit_btn_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/logout_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_1.setIcon(icon5)
        self.exit_btn_1.setIconSize(QtCore.QSize(32, 32))
        self.exit_btn_1.setObjectName("exit_btn_1")
        self.verticalLayout_3.addWidget(self.exit_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setStyleSheet("    #full_menu_widget {\n"
"        background-color: #313a46;\n"
"    }\n"
"\n"
"    /* style for QPushButton */\n"
"    #full_menu_widget QPushButton {\n"
"        border:none;\n"
"        border-radius: 3px;\n"
"        text-align: left;\n"
"        padding: 4px 10px 8px 15px;\n"
"        color: #f2f3f4;\n"
"        background-color: #313a46;\n"
"    }\n"
"\n"
"    #full_menu_widget QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    #full_menu_widget QPushButton:checked {\n"
"        color: #fff;\n"
"    }")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label_2.setMinimumSize(QtCore.QSize(64, 64))
        self.logo_label_2.setMaximumSize(QtCore.QSize(64, 64))
        self.logo_label_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.logo_label_2.setText("")
        self.logo_label_2.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/healthcare.png"))
        self.logo_label_2.setScaledContents(True)
        self.logo_label_2.setObjectName("logo_label_2")
        self.horizontalLayout_2.addWidget(self.logo_label_2)
        self.logo_label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logo_label_3.setFont(font)
        self.logo_label_3.setStyleSheet("    #logo_label_3 {\n"
"        padding: 5px;\n"
"        color: #fff;\n"
"        \n"
"    background-color: rgba(0, 0, 0,0);\n"
"    }")
        self.logo_label_3.setObjectName("logo_label_3")
        self.horizontalLayout_2.addWidget(self.logo_label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.home_btn_2.setFont(font)
        self.home_btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_btn_2.setAutoFillBackground(False)
        self.home_btn_2.setStyleSheet("")
        self.home_btn_2.setIcon(icon1)
        self.home_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.verticalLayout_2.addWidget(self.home_btn_2)
        self.newprofile_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.newprofile_btn_2.setFont(font)
        self.newprofile_btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newprofile_btn_2.setStyleSheet("")
        self.newprofile_btn_2.setIcon(icon2)
        self.newprofile_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.newprofile_btn_2.setCheckable(True)
        self.newprofile_btn_2.setAutoExclusive(True)
        self.newprofile_btn_2.setObjectName("newprofile_btn_2")
        self.verticalLayout_2.addWidget(self.newprofile_btn_2)
        self.display_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.display_btn_2.setFont(font)
        self.display_btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.display_btn_2.setStyleSheet("")
        self.display_btn_2.setIcon(icon3)
        self.display_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.display_btn_2.setCheckable(True)
        self.display_btn_2.setAutoExclusive(True)
        self.display_btn_2.setObjectName("display_btn_2")
        self.verticalLayout_2.addWidget(self.display_btn_2)
        self.uart_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.uart_btn_2.sizePolicy().hasHeightForWidth())
        self.uart_btn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.uart_btn_2.setFont(font)
        self.uart_btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.uart_btn_2.setStyleSheet("")
        self.uart_btn_2.setIcon(icon4)
        self.uart_btn_2.setIconSize(QtCore.QSize(24, 24))
        self.uart_btn_2.setCheckable(True)
        self.uart_btn_2.setAutoExclusive(True)
        self.uart_btn_2.setObjectName("uart_btn_2")
        self.verticalLayout_2.addWidget(self.uart_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.exit_btn_2.setFont(font)
        self.exit_btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.exit_btn_2.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/logout_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit_btn_2.setIcon(icon6)
        self.exit_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.change_btn = QtWidgets.QPushButton(self.widget)
        self.change_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.change_btn.setStyleSheet("    #change_btn {\n"
"        padding: 5px;\n"
"        border: none;\n"
"        width: 30px;\n"
"        height: 30px;\n"
"    }")
        self.change_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/sidebar_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon7)
        self.change_btn.setIconSize(QtCore.QSize(24, 24))
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_4.addWidget(self.change_btn)
        spacerItem2 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.page_3)
        self.widget_2.setObjectName("widget_2")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setGeometry(QtCore.QRect(318, 0, 1000, 831))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("")
        self.frame.setInputMethodHints(QtCore.Qt.ImhNone)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(340, 20, 320, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 85, 127);")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 120, 112, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(150, 200, 130, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_fullname = QtWidgets.QLineEdit(self.frame)
        self.line_fullname.setGeometry(QtCore.QRect(272, 120, 508, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.line_fullname.setFont(font)
        self.line_fullname.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0,255);\n"
"border-radius: 5px;\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_fullname.setText("")
        self.line_fullname.setPlaceholderText("")
        self.line_fullname.setObjectName("line_fullname")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(290, 200, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dateEdit.setStyleSheet("/* Style for header area  ####################################################*/ \n"
"\n"
"QCalendarWidget QWidget {\n"
"     alternate-background-color: #B8E2FF;\n"
"}\n"
"\n"
"/* style for top navigation area ###############################################*/ \n"
"\n"
"QDateEdit QWidget#qt_calendar_navigationbar {\n"
"    background-color: #fff;\n"
"    border: 2px solid  #B8E2FF;\n"
"    border-bottom: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* style for month change buttons ############################################ */\n"
"\n"
"QDateEdit QWidget#qt_calendar_prevmonth, \n"
"QDateEdit QWidget#qt_calendar_nextmonth {\n"
"    /* border delete */\n"
"    border: none;  \n"
"    /* delete default icons */\n"
"    qproperty-icon: none; \n"
"    \n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"\n"
"    border-radius: 5px; \n"
"    /* set background transparent */\n"
"    background-color: transparent; \n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* style for pre month button ############################################ */\n"
"\n"
"QDateEdit QWidget#qt_calendar_prevmonth {\n"
"    /* set text for button */\n"
"    /*qproperty-text: \">\";*/\n"
"    margin-left:5px;\n"
"    image: url(:/icon/Icon_Logo/arrow-119-48.ico);\n"
"}\n"
"\n"
"/* style for next month button ########################################### */\n"
"QDateEdit QWidget#qt_calendar_nextmonth {\n"
"    margin-right:5px;\n"
"    image: url(:/icon/Icon_Logo/arrow-19-48.ico);\n"
"    /* qproperty-text: \">\"; */\n"
"}\n"
"QDateEdit QWidget#qt_calendar_prevmonth:hover, \n"
"QDateEdit QWidget#qt_calendar_nextmonth:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_prevmonth:pressed, \n"
"QDateEdit QWidget#qt_calendar_nextmonth:pressed {\n"
"    background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"\n"
"/* Style for month and yeat buttons #################################### */\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearbutton {\n"
"    color: #000;\n"
"    margin:5px;\n"
"    border-radius: 5px;\n"
"    font-size: 13px;\n"
"    padding:0px 10px;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_monthbutton {\n"
"    width: 110px;\n"
"    color: #000;\n"
"    font-size: 13px;\n"
"    margin:5px 0px;\n"
"    border-radius: 5px;\n"
"    padding:0px 2px;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearbutton:hover, \n"
"QDateEdit QWidget#qt_calendar_monthbutton:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearbutton:pressed, \n"
"QDateEdit QWidget#qt_calendar_monthbutton:pressed {\n"
"    background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"/* Style for year input lineEdit ######################################*/\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearedit {\n"
"    min-width: 53px;\n"
"    color: #000;\n"
"    background: transparent;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Style for year change buttons ######################################*/\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearedit::up-button { \n"
"    image: url(:/icon/Icon_Logo/arrow-151-48.ico);\n"
"    subcontrol-position: right;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearedit::down-button { \n"
"    image: url(:/icon/Icon_Logo/arrow-213-48.ico);\n"
"    subcontrol-position: left; \n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearedit::down-button, \n"
"QDateEdit QWidget#qt_calendar_yearedit::up-button {\n"
"    width:10px;\n"
"    padding: 0px 5px;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QDateEdit QWidget#qt_calendar_yearedit::down-button:hover, \n"
"QDateEdit QWidget#qt_calendar_yearedit::up-button:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"/* Style for month select menu ##################################### */\n"
"\n"
"QDateEdit QCalendarWidget QToolButton QMenu {\n"
"     background-color: white;\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton QMenu::item {\n"
"    /*padding: 10px;*/\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton QMenu::item:selected:enabled {\n"
"    background-color: #55aa7f;\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton::menu-indicator {\n"
"    /* Remove toolButton arrow */\n"
"      /*image: none; */\n"
"    nosubcontrol-origin: margin;\n"
"    subcontrol-position: right center;\n"
"    margin-top: 10px;\n"
"    width:20px;\n"
"}\n"
"\n"
"/* Style for calendar table ########################################## */\n"
"\n"
"QDateEdit QCalendarWidget QTableView {\n"
"    /* Remove the selected dashed box */\n"
"    outline: 0px;\n"
"\n"
"    border: 2px solid  #B8E2FF;\n"
"    border-top: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QTableView::item:hover {\n"
"   border-radius:5px;\n"
"    background-color:#aaffff;\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QTableView::item:selected {\n"
"    background-color: #55aa7f; \n"
"    border-radius:5px;\n"
"}")
        self.dateEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(540, 200, 50, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(600, 200, 180, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox.setStyleSheet("#comboBox {\n"
"    border: 1px solid #000;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#comboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"#comboBox::down-arrow {\n"
"    image: url(:/icon/Icon_Logo/arrow-204-32.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right:15px;\n"
"}\n"
"\n"
"#comboBox:on {\n"
"     border: 2px solid #c2dbfe;\n"
" }\n"
"\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    padding:5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;  /*去虚线*/\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    background-color:#FFFFFF;\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}\n"
"\n"
"")
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line_height = QtWidgets.QLineEdit(self.frame)
        self.line_height.setGeometry(QtCore.QRect(290, 360, 80, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_height.setFont(font)
        self.line_height.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0,255);\n"
"border-radius: 5px;\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_height.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_height.setText("")
        self.line_height.setPlaceholderText("")
        self.line_height.setObjectName("line_height")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(150, 360, 130, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_weight = QtWidgets.QLineEdit(self.frame)
        self.line_weight.setGeometry(QtCore.QRect(560, 360, 220, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_weight.setFont(font)
        self.line_weight.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0,255);\n"
"border-radius: 5px;\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_weight.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_weight.setText("")
        self.line_weight.setPlaceholderText("")
        self.line_weight.setObjectName("line_weight")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(410, 360, 140, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_insur_number = QtWidgets.QLineEdit(self.frame)
        self.line_insur_number.setGeometry(QtCore.QRect(450, 520, 330, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_insur_number.setFont(font)
        self.line_insur_number.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0,255);\n"
"border-radius: 5px;\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_insur_number.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_insur_number.setText("")
        self.line_insur_number.setPlaceholderText("")
        self.line_insur_number.setObjectName("line_insur_number")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(150, 520, 290, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.line_address = QtWidgets.QLineEdit(self.frame)
        self.line_address.setGeometry(QtCore.QRect(260, 280, 520, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_address.setFont(font)
        self.line_address.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0,255);\n"
"border-radius: 5px;\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_address.setText("")
        self.line_address.setPlaceholderText("")
        self.line_address.setObjectName("line_address")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(150, 280, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.line_note = QtWidgets.QLineEdit(self.frame)
        self.line_note.setGeometry(QtCore.QRect(220, 600, 560, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_note.setFont(font)
        self.line_note.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0,255);\n"
"border-radius: 5px;\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_note.setText("")
        self.line_note.setObjectName("line_note")
        self.line_phone_number = QtWidgets.QLineEdit(self.frame)
        self.line_phone_number.setGeometry(QtCore.QRect(330, 440, 450, 35))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_phone_number.setFont(font)
        self.line_phone_number.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0,255);\n"
"border-radius: 5px;\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_phone_number.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_phone_number.setText("")
        self.line_phone_number.setPlaceholderText("")
        self.line_phone_number.setObjectName("line_phone_number")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(150, 440, 170, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(150, 600, 60, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.clear_button = QtWidgets.QPushButton(self.frame)
        self.clear_button.setGeometry(QtCore.QRect(530, 700, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.clear_button.setFont(font)
        self.clear_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clear_button.setStyleSheet("QPushButton#clear_button{    \n"
"    background-color: rgba(21, 122, 110,255);\n"
"    color:white;\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton#clear_button:hover{    \n"
"    background-color: rgba(21, 122, 110,200);\n"
"}\n"
"QPushButton#clear_button:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgba(17, 98, 87,200);\n"
"}")
        self.clear_button.setObjectName("clear_button")
        self.save_button = QtWidgets.QPushButton(self.frame)
        self.save_button.setGeometry(QtCore.QRect(370, 700, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.save_button.setFont(font)
        self.save_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.save_button.setStyleSheet("QPushButton#save_button{    \n"
"    background-color: rgba(239, 35, 60,255);\n"
"    color:white;\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton#save_button:hover{    \n"
"    background-color: rgba(239, 35, 60,200);\n"
"}\n"
"QPushButton#save_button:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgba(229, 56, 59,200);\n"
"}")
        self.save_button.setObjectName("save_button")
        self.gridLayout_4.addWidget(self.widget_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.page_4)
        self.widget_4.setObjectName("widget_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_2.setGeometry(QtCore.QRect(320, 15, 211, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_2.setStyleSheet("#comboBox_2 {\n"
"    border: 1px solid #000;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#comboBox_2::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"#comboBox_2::down-arrow {\n"
"    image: url(:/icon/Icon_Logo/arrow-204-32.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right:15px;\n"
"}\n"
"\n"
"#comboBox_2:on {\n"
"     border: 2px solid #c2dbfe;\n"
" }\n"
"\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    padding:5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;  /*去虚线*/\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    background-color:#FFFFFF;\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}\n"
"\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.widget_4)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 60, 1632, 771))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_dashboard = QtWidgets.QWidget()
        self.page_dashboard.setObjectName("page_dashboard")
        self.label_14 = QtWidgets.QLabel(self.page_dashboard)
        self.label_14.setGeometry(QtCore.QRect(664, 10, 330, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(113, 97, 239);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.widget_doctors = QtWidgets.QWidget(self.page_dashboard)
        self.widget_doctors.setGeometry(QtCore.QRect(272, 130, 420, 130))
        self.widget_doctors.setStyleSheet("border:1px solid rgba(190, 191, 197, 255);\n"
"border-radius: 15px;\n"
"")
        self.widget_doctors.setObjectName("widget_doctors")
        self.label_15 = QtWidgets.QLabel(self.widget_doctors)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 71, 110))
        self.label_15.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/doctor.png"))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget_doctors)
        self.label_16.setGeometry(QtCore.QRect(180, 30, 102, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_number_doctors = QtWidgets.QLabel(self.widget_doctors)
        self.label_number_doctors.setGeometry(QtCore.QRect(110, 27, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_number_doctors.setFont(font)
        self.label_number_doctors.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(0, 0, 0,255)")
        self.label_number_doctors.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_doctors.setObjectName("label_number_doctors")
        self.label_17 = QtWidgets.QLabel(self.widget_doctors)
        self.label_17.setGeometry(QtCore.QRect(110, 73, 271, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.widget_patients = QtWidgets.QWidget(self.page_dashboard)
        self.widget_patients.setGeometry(QtCore.QRect(966, 130, 420, 130))
        self.widget_patients.setStyleSheet("border:1px solid rgba(190, 191, 197, 255);\n"
"border-radius: 15px;\n"
"")
        self.widget_patients.setObjectName("widget_patients")
        self.label_18 = QtWidgets.QLabel(self.widget_patients)
        self.label_18.setGeometry(QtCore.QRect(30, 10, 71, 110))
        self.label_18.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/patient.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_patients)
        self.label_19.setGeometry(QtCore.QRect(180, 30, 102, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_number_patients = QtWidgets.QLabel(self.widget_patients)
        self.label_number_patients.setGeometry(QtCore.QRect(110, 27, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_number_patients.setFont(font)
        self.label_number_patients.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(0, 0, 0,255)")
        self.label_number_patients.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_patients.setObjectName("label_number_patients")
        self.label_20 = QtWidgets.QLabel(self.widget_patients)
        self.label_20.setGeometry(QtCore.QRect(110, 73, 271, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.widget_male = QtWidgets.QWidget(self.page_dashboard)
        self.widget_male.setGeometry(QtCore.QRect(1180, 400, 190, 190))
        self.widget_male.setStyleSheet("border-radius: 15px;\n"
"border: 1px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(25, 118, 210, 255), stop:0.55 rgba(21, 101, 192, 255), stop:0.98 rgba(0, 41, 107, 255));")
        self.widget_male.setObjectName("widget_male")
        self.label_21 = QtWidgets.QLabel(self.widget_male)
        self.label_21.setGeometry(QtCore.QRect(110, 110, 81, 81))
        self.label_21.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/male-white.png"))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_male)
        self.label_22.setGeometry(QtCore.QRect(100, -10, 81, 81))
        self.label_22.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/male.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_per_male = QtWidgets.QLabel(self.widget_male)
        self.label_per_male.setGeometry(QtCore.QRect(20, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_per_male.setFont(font)
        self.label_per_male.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_per_male.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_per_male.setObjectName("label_per_male")
        self.label_24 = QtWidgets.QLabel(self.widget_male)
        self.label_24.setGeometry(QtCore.QRect(90, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_number_male = QtWidgets.QLabel(self.widget_male)
        self.label_number_male.setGeometry(QtCore.QRect(20, 110, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_number_male.setFont(font)
        self.label_number_male.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_number_male.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_number_male.setObjectName("label_number_male")
        self.widget_female = QtWidgets.QWidget(self.page_dashboard)
        self.widget_female.setGeometry(QtCore.QRect(980, 400, 190, 190))
        self.widget_female.setStyleSheet("border-radius: 15px;\n"
"border: 1px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 179, 198, 255), stop:0.55 rgba(255, 143, 171, 255), stop:0.98 rgba(251, 111, 146, 255));")
        self.widget_female.setObjectName("widget_female")
        self.label_23 = QtWidgets.QLabel(self.widget_female)
        self.label_23.setGeometry(QtCore.QRect(110, 110, 81, 81))
        self.label_23.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/female-white.png"))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.widget_female)
        self.label_25.setGeometry(QtCore.QRect(100, -10, 81, 81))
        self.label_25.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/icon/Icon_Logo/female.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_per_female = QtWidgets.QLabel(self.widget_female)
        self.label_per_female.setGeometry(QtCore.QRect(20, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_per_female.setFont(font)
        self.label_per_female.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_per_female.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_per_female.setObjectName("label_per_female")
        self.label_26 = QtWidgets.QLabel(self.widget_female)
        self.label_26.setGeometry(QtCore.QRect(90, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_number_female = QtWidgets.QLabel(self.widget_female)
        self.label_number_female.setGeometry(QtCore.QRect(20, 110, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_number_female.setFont(font)
        self.label_number_female.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_number_female.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_number_female.setObjectName("label_number_female")
        self.widget_ave_age = QtWidgets.QWidget(self.page_dashboard)
        self.widget_ave_age.setGeometry(QtCore.QRect(102, 345, 760, 300))
        self.widget_ave_age.setStyleSheet("border:1px solid rgba(190, 191, 197, 255);\n"
"border-radius: 15px;\n"
"")
        self.widget_ave_age.setObjectName("widget_ave_age")
        self.label_28 = QtWidgets.QLabel(self.widget_ave_age)
        self.label_28.setGeometry(QtCore.QRect(50, 10, 301, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_ages = QtWidgets.QLabel(self.widget_ave_age)
        self.label_ages.setGeometry(QtCore.QRect(350, 10, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_ages.setFont(font)
        self.label_ages.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(0, 0, 0,255)")
        self.label_ages.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ages.setObjectName("label_ages")
        self.widget_plot = QtWidgets.QWidget(self.widget_ave_age)
        self.widget_plot.setGeometry(QtCore.QRect(10, 50, 741, 240))
        self.widget_plot.setStyleSheet("border-color: rgba(255, 255, 255,0);")
        self.widget_plot.setObjectName("widget_plot")
        self.stackedWidget_2.addWidget(self.page_dashboard)
        self.page_ecg = QtWidgets.QWidget()
        self.page_ecg.setObjectName("page_ecg")
        self.label_27 = QtWidgets.QLabel(self.page_ecg)
        self.label_27.setGeometry(QtCore.QRect(664, 10, 330, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(113, 97, 239);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.widget_data = QtWidgets.QWidget(self.page_ecg)
        self.widget_data.setGeometry(QtCore.QRect(960, 70, 600, 172))
        self.widget_data.setStyleSheet("border:1px solid rgba(190, 191, 197, 255);\n"
"border-radius: 15px;\n"
"")
        self.widget_data.setObjectName("widget_data")
        self.label_30 = QtWidgets.QLabel(self.widget_data)
        self.label_30.setGeometry(QtCore.QRect(20, 10, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_fullname = QtWidgets.QLabel(self.widget_data)
        self.label_fullname.setGeometry(QtCore.QRect(120, 8, 461, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_fullname.setFont(font)
        self.label_fullname.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_fullname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_fullname.setObjectName("label_fullname")
        self.label_31 = QtWidgets.QLabel(self.widget_data)
        self.label_31.setGeometry(QtCore.QRect(20, 50, 120, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_dob = QtWidgets.QLabel(self.widget_data)
        self.label_dob.setGeometry(QtCore.QRect(140, 48, 150, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_dob.setFont(font)
        self.label_dob.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_dob.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_dob.setObjectName("label_dob")
        self.label_32 = QtWidgets.QLabel(self.widget_data)
        self.label_32.setGeometry(QtCore.QRect(370, 50, 50, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.label_sex = QtWidgets.QLabel(self.widget_data)
        self.label_sex.setGeometry(QtCore.QRect(420, 48, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_sex.setFont(font)
        self.label_sex.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_sex.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_sex.setObjectName("label_sex")
        self.label_33 = QtWidgets.QLabel(self.widget_data)
        self.label_33.setGeometry(QtCore.QRect(20, 130, 150, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.label_phone = QtWidgets.QLabel(self.widget_data)
        self.label_phone.setGeometry(QtCore.QRect(170, 128, 161, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_phone.setFont(font)
        self.label_phone.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_phone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_phone.setObjectName("label_phone")
        self.label_insur = QtWidgets.QLabel(self.widget_data)
        self.label_insur.setGeometry(QtCore.QRect(270, 88, 120, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_insur.setFont(font)
        self.label_insur.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_insur.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_insur.setObjectName("label_insur")
        self.label_34 = QtWidgets.QLabel(self.widget_data)
        self.label_34.setGeometry(QtCore.QRect(20, 90, 250, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgba(111, 113, 120,255)")
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.comboBox_name = QtWidgets.QComboBox(self.page_ecg)
        self.comboBox_name.setGeometry(QtCore.QRect(506, 70, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.comboBox_name.setFont(font)
        self.comboBox_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_name.setStyleSheet("#comboBox_name {\n"
"    border: 1px solid #000;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#comboBox_name::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"#comboBox_name::down-arrow {\n"
"    image: url(:/icon/Icon_Logo/arrow-204-32.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right:15px;\n"
"}\n"
"\n"
"#comboBox_name:on {\n"
"     border: 2px solid #c2dbfe;\n"
" }\n"
"\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    padding:5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;  /*去虚线*/\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    background-color:#FFFFFF;\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}\n"
"\n"
"")
        self.comboBox_name.setObjectName("comboBox_name")
        self.label_29 = QtWidgets.QLabel(self.page_ecg)
        self.label_29.setGeometry(QtCore.QRect(66, 70, 430, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(87, 16, 137);")
        self.label_29.setObjectName("label_29")
        self.comboBox_date = QtWidgets.QComboBox(self.page_ecg)
        self.comboBox_date.setGeometry(QtCore.QRect(506, 130, 241, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.comboBox_date.setFont(font)
        self.comboBox_date.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_date.setStyleSheet("#comboBox_date {\n"
"    border: 1px solid #000;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#comboBox_date::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"#comboBox_date::down-arrow {\n"
"    image: url(:/icon/Icon_Logo/arrow-204-32.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right:15px;\n"
"}\n"
"\n"
"#comboBox_date:on {\n"
"     border: 2px solid #c2dbfe;\n"
" }\n"
"\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    padding:5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;  /*去虚线*/\n"
"}\n"
"\n"
"QComboBox QListView::item{\n"
"    padding-left:10px;\n"
"    background-color:#FFFFFF;\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}\n"
"\n"
"")
        self.comboBox_date.setObjectName("comboBox_date")
        self.label_35 = QtWidgets.QLabel(self.page_ecg)
        self.label_35.setGeometry(QtCore.QRect(66, 130, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(87, 16, 137);")
        self.label_35.setObjectName("label_35")
        self.widget_plot_ecg = QtWidgets.QWidget(self.page_ecg)
        self.widget_plot_ecg.setGeometry(QtCore.QRect(66, 250, 1500, 520))
        self.widget_plot_ecg.setObjectName("widget_plot_ecg")
        self.label_36 = QtWidgets.QLabel(self.widget_plot_ecg)
        self.label_36.setGeometry(QtCore.QRect(550, 0, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(113, 97, 239);")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.widget_ecg_graph = QtWidgets.QWidget(self.widget_plot_ecg)
        self.widget_ecg_graph.setGeometry(QtCore.QRect(-1, 50, 1500, 470))
        self.widget_ecg_graph.setObjectName("widget_ecg_graph")
        self.start_button = QtWidgets.QPushButton(self.page_ecg)
        self.start_button.setGeometry(QtCore.QRect(750, 120, 105, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.start_button.setFont(font)
        self.start_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start_button.setStyleSheet("QPushButton#start_button{    \n"
"    background-color: rgba(224, 195, 252,255);\n"
"    color:rgb(87, 16, 137);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton#start_button:hover{    \n"
"    background-color: rgba(224, 195, 252,200);\n"
"}\n"
"QPushButton#start_button:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgba(184, 156, 208,200);\n"
"}")
        self.start_button.setObjectName("start_button")
        self.stackedWidget_2.addWidget(self.page_ecg)
        self.page_history = QtWidgets.QWidget()
        self.page_history.setObjectName("page_history")
        self.label_37 = QtWidgets.QLabel(self.page_history)
        self.label_37.setGeometry(QtCore.QRect(720, 355, 192, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.stackedWidget_2.addWidget(self.page_history)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setGeometry(QtCore.QRect(50, 15, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.widget_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.serialMonitor_V = test_visualize.MainWindow()
        self.gridLayout_6.addWidget(self.serialMonitor_V, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        # self.label_8 = QtWidgets.QLabel(self.page_5)
        # font = QtGui.QFont()
        # font.setPointSize(20)
        # self.label_8.setFont(font)
        # self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_8.setObjectName("label_8")
        # self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        # self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.comboBox.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(2)
        self.change_btn.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_btn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.home_btn_1.toggled['bool'].connect(self.home_btn_2.setChecked) # type: ignore
        self.newprofile_btn_1.toggled['bool'].connect(self.newprofile_btn_2.setChecked) # type: ignore
        self.display_btn_1.toggled['bool'].connect(self.display_btn_2.setChecked) # type: ignore
        self.uart_btn_1.toggled['bool'].connect(self.uart_btn_2.setChecked) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.home_btn_1.setChecked) # type: ignore
        self.newprofile_btn_2.toggled['bool'].connect(self.newprofile_btn_1.setChecked) # type: ignore
        self.display_btn_2.toggled['bool'].connect(self.display_btn_1.setChecked) # type: ignore
        self.uart_btn_2.toggled['bool'].connect(self.uart_btn_1.setChecked) # type: ignore
        self.exit_btn_2.clicked.connect(MainWindow.close) # type: ignore
        self.exit_btn_1.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Health Monitoring System"))
        self.logo_label_3.setText(_translate("MainWindow", "Project_2"))
        self.home_btn_2.setText(_translate("MainWindow", "Home"))
        self.newprofile_btn_2.setText(_translate("MainWindow", "Create New Profile"))
        self.display_btn_2.setText(_translate("MainWindow", "Display"))
        self.uart_btn_2.setText(_translate("MainWindow", "UART"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))
        self.label_5.setText(_translate("MainWindow", "HomePage"))
        self.label.setText(_translate("MainWindow", "Create New Profile"))
        self.label_2.setText(_translate("MainWindow", "Full Name:"))
        self.label_3.setText(_translate("MainWindow", "Day of Birth:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.label_4.setText(_translate("MainWindow", "Sex:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Female"))
        self.label_6.setText(_translate("MainWindow", "Height (cm):"))
        self.label_9.setText(_translate("MainWindow", "Weight (kg):"))
        self.label_10.setText(_translate("MainWindow", "Health Insurance Number:"))
        self.label_11.setText(_translate("MainWindow", "Address:"))
        self.line_note.setPlaceholderText(_translate("MainWindow", "Note here if the patient has underlying disease."))
        self.label_13.setText(_translate("MainWindow", "Phone Number:"))
        self.label_12.setText(_translate("MainWindow", "Note:"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "System Overview"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Patient\'s Data"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Patient\'s History"))
        self.label_14.setText(_translate("MainWindow", "SYSTEM OVERVIEW"))
        self.label_16.setText(_translate("MainWindow", "Doctors"))
        self.label_number_doctors.setText(_translate("MainWindow", "123"))
        self.label_17.setText(_translate("MainWindow", "Total Available Doctors"))
        self.label_19.setText(_translate("MainWindow", "Patients"))
        self.label_number_patients.setText(_translate("MainWindow", "456"))
        self.label_20.setText(_translate("MainWindow", "Total Available Registrants"))
        self.label_per_male.setText(_translate("MainWindow", "59.87"))
        self.label_24.setText(_translate("MainWindow", "%"))
        self.label_number_male.setText(_translate("MainWindow", "273"))
        self.label_per_female.setText(_translate("MainWindow", "40.13"))
        self.label_26.setText(_translate("MainWindow", "%"))
        self.label_number_female.setText(_translate("MainWindow", "183"))
        self.label_28.setText(_translate("MainWindow", "Average Ages of Patients"))
        self.label_ages.setText(_translate("MainWindow", "50.00"))
        self.label_27.setText(_translate("MainWindow", "Patient\'s Data"))
        self.label_30.setText(_translate("MainWindow", "Full name:"))
        self.label_fullname.setText(_translate("MainWindow", "None"))
        self.label_31.setText(_translate("MainWindow", "Day of birth:"))
        self.label_dob.setText(_translate("MainWindow", "None"))
        self.label_32.setText(_translate("MainWindow", "Sex:"))
        self.label_sex.setText(_translate("MainWindow", "None"))
        self.label_33.setText(_translate("MainWindow", "Phone number:"))
        self.label_phone.setText(_translate("MainWindow", "None"))
        self.label_insur.setText(_translate("MainWindow", "None"))
        self.label_34.setText(_translate("MainWindow", "Health Insurance Number:"))
        self.label_29.setText(_translate("MainWindow", "Select Fullname/Health Insurance Number:"))
        self.label_35.setText(_translate("MainWindow", "Select measurement date:"))
        self.label_36.setText(_translate("MainWindow", "Electrocardiogram (ECG)"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.label_37.setText(_translate("MainWindow", "Maintenance"))
        self.label_7.setText(_translate("MainWindow", "Select Display\'s category:"))
        # self.label_8.setText(_translate("MainWindow", "UART"))
import img_src_rc
