# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import img_src_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon_Logo/healthcare.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(770, 300, 380, 480))
        self.widget.setStyleSheet("QPushButton#sign_inButton{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#sign_inButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#sign_inButton:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(15, 10, 350, 460))
        self.label.setStyleSheet("border-image: url(:/icon/Icon_Logo/stone-texture.jpg);\n"
"border-radius:20px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 25, 320, 430))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,20);\n"
"border-radius:15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_signup = QtWidgets.QLabel(self.widget)
        self.label_signup.setEnabled(True)
        self.label_signup.setGeometry(QtCore.QRect(30, 50, 320, 45))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_signup.setFont(font)
        self.label_signup.setTabletTracking(False)
        self.label_signup.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_signup.setAutoFillBackground(False)
        self.label_signup.setStyleSheet("background-color: rgba(0,0,0,0)\n"
"")
        self.label_signup.setAlignment(QtCore.Qt.AlignCenter)
        self.label_signup.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_signup.setObjectName("label_signup")
        self.line_username = QtWidgets.QLineEdit(self.widget)
        self.line_username.setGeometry(QtCore.QRect(80, 150, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_username.setFont(font)
        self.line_username.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(0, 0, 0,255);\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_username.setText("")
        self.line_username.setObjectName("line_username")
        self.line_password = QtWidgets.QLineEdit(self.widget)
        self.line_password.setGeometry(QtCore.QRect(80, 220, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.line_password.setFont(font)
        self.line_password.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(0, 0, 0,255);\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom:5px")
        self.line_password.setText("")
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.sign_inButton = QtWidgets.QPushButton(self.widget)
        self.sign_inButton.setGeometry(QtCore.QRect(90, 300, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.sign_inButton.setFont(font)
        self.sign_inButton.setObjectName("sign_inButton")
        self.label_createnew = QtWidgets.QLabel(self.widget)
        self.label_createnew.setGeometry(QtCore.QRect(75, 370, 145, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setKerning(False)
        self.label_createnew.setFont(font)
        self.label_createnew.setAutoFillBackground(False)
        self.label_createnew.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.label_createnew.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_createnew.setObjectName("label_createnew")
        self.createButton = QtWidgets.QPushButton(self.widget)
        self.createButton.setGeometry(QtCore.QRect(220, 365, 85, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(False)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none")
        self.createButton.setObjectName("createButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Health Monitoring System"))
        self.label_signup.setText(_translate("MainWindow", "Sign in"))
        self.line_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.line_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.sign_inButton.setText(_translate("MainWindow", "Sign in"))
        self.label_createnew.setText(_translate("MainWindow", "Don\'t have account?"))
        self.createButton.setText(_translate("MainWindow", "Create one"))

